### ISSUE TITLE
Where can I get "LDAP User Info Addon v0.2"?

### ISSUE THREAD

**Issue by timmerk** [Chefkeks/osTicket-Addons#4]
Did you mean the "LDAP Authentication and Lookup" plugin, instead?

**Comment by timmerk** [comment]
Nevermind, I guess the module itself is "LDAP User Info Addon". You might want to remove that as a requirement from the Read Me, since it doesn't make sense to include itself as a required dependency for itself.

**Comment by Chefkeks** [comment]
Thank you for ponting that out!

No I didn't mean the "LDAP Authentication and Lookup".

I'll correct the readme next week and delete the dependency of the module/addon for itself :D

Cheers!
Michael

**Comment by timmerk** [comment]
"LDAP User Info Addon v0.2 or newer" still shows up in the Read Me

**Comment by Chefkeks** [comment]
I thought I removed that line - looks like I didn't do.
Thank you for pointing out a second time - this time I really deleted that unnecessary requirement line :)
